services:
  webhook:
    image: almir/webhook
    container_name: pokelist-webhook
    restart: unless-stopped
    volumes:
      - /mnt/ssd/pokelist/deploy/webhook.json:/etc/webhook/hooks.json
      - /mnt/ssd/pokelist:/mnt/ssd/pokelist
    ports:
      - "9000:9000"
    command: ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload"]
